name: smart_grocery_list
description: A smart grocery list app with Firebase integration

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

  # QR Code functionality
  qr_flutter: ^4.1.0         # For QR code generation
  mobile_scanner: ^3.5.7     # For QR code scanning (updated version)

  # Storage and utilities
  shared_preferences: ^2.2.2

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google_logo.png
    - assets/images/applogo.png
  